apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0lvp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0lvp
    app.kubernetes.io/part-of: tkwch-fix-0075-0043-app
  name: devfile-sample-0lvp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0lvp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0lvp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0043-tenant/tkwch-fix-0075-0043-app/devfile-sample-0lvp@sha256:5330c5781f15f94f7cabd76e7a4c2bde8e428e4f8f6f36fd7b5d52eb050fc357
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
